### ISSUE TITLE
query.LookupRelease Error when including MetaBrainz.MusicBrainz.Include.Recordings

### ISSUE THREAD

**Issue by LLloody** [Zastai/MusicBrainz#2]
Message=Could not find member 'position' on object of type 'Track'. Path 'media[0].tracks[0].position', line 1, position 910.
  Source=Newtonsoft.Json
when calling:
MetaBrainz.MusicBrainz.Interfaces.Entities.IRelease rls = qry.LookupRelease(mbid,
                         MetaBrainz.MusicBrainz.Include.Media
                        | MetaBrainz.MusicBrainz.Include.Artists
                        | MetaBrainz.MusicBrainz.Include.Aliases
                        | MetaBrainz.MusicBrainz.Include.Labels
                        | MetaBrainz.MusicBrainz.Include.Collections
                        | MetaBrainz.MusicBrainz.Include.ArtistRelationships
                        | MetaBrainz.MusicBrainz.Include.ReleaseRelationships
                        | MetaBrainz.MusicBrainz.Include.UrlRelationships
                        | MetaBrainz.MusicBrainz.Include.RecordingRelationships
                        | MetaBrainz.MusicBrainz.Include.WorkRelationships
                        | MetaBrainz.MusicBrainz.Include.Isrcs
                        | MetaBrainz.MusicBrainz.Include.ReleaseGroups
                        | MetaBrainz.MusicBrainz.Include.Recordings
                        );

**Comment by Zastai** [comment]
In order for me to reproduce this, it's always helpful to include the specific MBID being used.

However, the schema has it as optional, so I'll mark it like that.

I also see that the server is sending null as artist-credit value for a release group requested this way (before it did not send the artist-credit field at all). I'll go through all my testcases again to see what else has been broken recently.

**Comment by Zastai** [comment]
Oh I see it was the other way around - I didn't have a position field for track at all. Odd oversight. Will add one.

**Comment by Zastai** [comment]
@LLloody Can you try an AppVeyor build (e.g. https://ci.appveyor.com/project/Zastai/musicbrainz/build/1.0.7-appveyor/job/o87sg1op29g7972u/artifacts) to see if that fixes it?

**Comment by LLloody** [comment]
Zast
Great job bud! the issue is resolved. I will continue testing the other packages and let u know If I find anything else
