### ISSUE TITLE
Json serialization error when retrieving recordings

### ISSUE THREAD

**Issue by colerus** [Zastai/MusicBrainz#3]
Firstly, congratulations for this great work, and thank you!

When calling method FindRecordings("mishka",100) an error is thrown: 

Newtonsoft.Json.JsonSerializationException: 'Required property 'format' not found in JSON. Path 'recordings[6].releases[0].media[0]', line 1, position 7605.'

I'm using the latest nuget packages.

**Comment by Zastai** [comment]
MB has been playing a little bit fast and loose with which fields it does or does not include in the json, which then bumps into my attempt at validating responses.
I think I’ll just make all fields other than the primary IDs optional and nullable; that way things should keep on working as long as no new fields are added.

**Comment by colerus** [comment]
I believe this workarround could work and we can threat this null fields in our side with no problems.
Thanks for the attention.

**Comment by Zastai** [comment]
I committed a fix for 3 cases that broke your example search.
I'm not pushing a new version until I review all the attributes (this weekend at the earliest); in the meantime you can either build your own, or take a nupkg from [AppVeyor](https://ci.appveyor.com/project/Zastai/musicbrainz/builds/20739259/artifacts).

**Comment by Zastai** [comment]
v1.1.2 was published today, should solve it.
