### ISSUE TITLE
Add support for genres and user-genres include items

### ISSUE THREAD

**Issue by stevenwdv** [Zastai/MusicBrainz#4]
https://musicbrainz.org/doc/Development/XML_Web_Service/Version_2#inc.3D says:
> All entities except release support:
> ```tags, user-tags, genres, user-genres```

But `genres` and `user-genres` are not supported yet by this library. It would be nice if you could add support for them! (In the mean time we can use regular tags.)

**Comment by Zastai** [comment]
Looks like these were added in March.
When I have a chance I'll go over all recent changes to that document and ensure I'm up to date.
(Also looks like genres are just tags filtered through a specific list.)

**Comment by Zastai** [comment]
Could you try with a current appveyor build to see if that works for you?
https://ci.appveyor.com/project/Zastai/musicbrainz/build/artifacts

**Comment by stevenwdv** [comment]
Yes this seems to work, thanks a lot!
